### PR TITLE
Initial commit for a BySNPListOfDiseases

### PR DESCRIPTION
**Pull request by paddie**
- added a simple template
  [#29552829]

### CODE REVIEW

**Comment by paddie** [comment]
For fixing the cache, there are two ways:
1. Either join together all the snpids and hash them (the processing time increases linearly by the number of SNPids)
2. Or, render for each SNPid and cache seperately.
3. First, force users to create a collection of these SNP-ids. _then_ generate the diseasebysnp-ids and cache on the collection-id.

Option **3.** would be optimal, but until we have the collection model, I'm using option **1.**

**Comment by paddie** [comment]
Check it out @DIKU-DevStudio/owners. For now its only a static list of snps; we need to work on the upload/snp insert stuff.. Decide which is best.

**Comment by jensraaby** [comment]
I get an error when trying to populate:
'str' object has no attribute 'trim'

**Comment by paddie** [comment]
Ha, a stack-dump would be more helpfull - but fixed.

**Comment by paddie** [comment]
I'm closing this, I've added this to another branch.

**Pull request closed without merging**
