### PR TITLE
Changed app id to perseqbeta

### PR DESCRIPTION
**Pull request by jensraaby**
To make sure we can demo to people in a more robust way, and to ensure the search API problems are not limited to the offline GAE SDK, I have created a new app ID for PerSeq.

### CODE REVIEW

**Comment by paddie** [comment]
Explain this to me - did the name have something to do with the fact that indexing didn't work?

**Comment by jensraaby** [comment]
No, but 1) we wanted to be able to see if it was also an issue on google's servers and 2) it would be nice to have a second app with some quota left :)

Jens

**Comment by jensraaby** [comment]
@paddie Is it safe to run populate() with the master branch? I'm thinking of setting the new appID up as a version for Lars to show to other people (i.e. a more stable deployment).

**Comment by paddie** [comment]
Aye, it worked when I was testing it

Hilsen

Patrick-Ranjit D. Madsen

Sent from my mobile. Please excuse any and all typos, errors,
formatting, lack of punctuation or short responses.

On 23/05/2012, at 15.49, jensraaby
reply@reply.github.com
wrote:

**Comment by paddie** [comment]
We don't really need this for now...

**Pull request closed without merging**
