### PR TITLE
Pydoc

### PR DESCRIPTION
**Pull request by wejendorp**
PyDoc seemed to suck, so I went for Sphinx instead (http://sphinx.pocoo.org/).
It does not automatically find modules, you add them to the docs/*.rst files where appropriate.

Also, requires you to setup the PYTHONPATH on your system to include the PerseQ folder before being able to run. This will also allow pylint to run properly if done!
pythons sys.path must contain google_appengine, google_appengine/lib/jinja2, google_appengine/lib/yaml/lib, google_appengine/lib/webob as well.

When the path is set, simply run "make html" from the docs folder, resulting in:
http://dl.dropbox.com/u/247397/sphinx/index.html

### CODE REVIEW

**Comment by jensraaby** [comment]
Really nice output :)

**Comment by paddie** [comment]
I can't run it though.. getting a

``` bash
paddieMBP:docs pamad$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
make: sphinx-build: No such file or directory
make: *** [html] Error 1
```

Where is this sphinx-build coming from?

**Comment by wejendorp** [comment]
Have you installed sphinx? You can do it via easy install
Den 11/05/2012 14.27 skrev "Patrick-Ranjit D. Madsen" <
reply@reply.github.com

**Comment by paddie** [comment]
Yeah, I got v. 2.0.2 but can't find any sphinx-build stuff

**Comment by paddie** [comment]
I'll just merge it, and let you guys explain it to me..

**Pull request merged**
