### PR TITLE
Models

### PR DESCRIPTION
**Pull request by jensraaby**
To track the work on this branch it would be good to have the pull request in place for commenting on individual lines of code etc.

### CODE REVIEW

**Comment by paddie** [comment]
Looks good. Interface issues:
1. comment field should be below comments, not on top
2. grading should be a drop-down 1-10 or 1-5 thing.
3. grade should be an average, statically calculated everytime someone votes.
4. should obviously be presented somewhere.

most importantly: **tests**.

**Comment by paddie** [comment]
Oh, and stop polluting this branch with annotations and logins.. this was a model pull-request :)

**Comment by paddie** [comment]
seriously, I'm merging this - we need to separate these commits @Wejendorp

**Comment by paddie** [comment]
Goes for @jensraaby too btw :)

**Comment by jensraaby** [comment]
This pull request has got me seriously confused - how did my WIP commits get merged in to this branch?

**Comment by paddie** [comment]
I have absolutely no idea.. I jumped back and forth like 10 times trying to figure out why we were down one pull-request.

**Comment by jensraaby** [comment]
Looks like Jacob pulled the commit into his branch and GitHub decided to close the pull request by itself

Jens

**Pull request merged**
