### PR TITLE
EPIC GWAS IMPORT ERROR

### PR DESCRIPTION
**Pull request by paddie**
I've been having fevery dreams these last couple of weeks, and I suddenly realized why. The import used one idiotic assumption when loading the GWAS. That each study only references a **single** disease. This, in retrospect, is obviously not the case, given that multiple GWAS correlations could possibly be identified in a study.

This means that each study now has a list of diseases they reference, instead of just one, and each disease now has many more studies to reference (possibly).

In other words, there is actually a many-to-many relationship between disease and study, whereas the old model only had a one disease to many studies relation.
- added disease <*----*> study relation
- updated templates to reflect this model change
- study no longer has a `study.disease_ref` but an array of keys

Since this fix obviously has implications on how we search for studies, I wanted to give @wejendorp a heads up. Since the "disease_trait" field is no longer there, replaced by an array of disease_keys  (I could add an additional disease_names string-array if that would simplify things?), you can no longer index the disease-field of the study. For now I've simply commented out that field in your indexing, and I couldn't figure out how to add indexing for arrays.

### CODE REVIEW

**Comment by paddie** [comment]
example url with an example of a study with multiple identified GWAS relations  `<localhost>/study/19010793`

remember to purge() and populate() first

**Comment by wejendorp** [comment]
Now the Study documents have a list of names of diseases (csv), and are fully searchable again.

**Comment by jensraaby** [comment]
Are we ready to close this one yet? Thinking we should be moving this off the production line so we can start on to the pagination story

**Comment by paddie** [comment]
Agreed, just want to be sure Jacob understands what happens to the indexer

Hilsen

Patrick-Ranjit D. Madsen

Sent from my mobile. Please excuse any and all typos, errors,
formatting, lack of punctuation or short responses.

On 01/06/2012, at 20.20, jensraaby
reply@reply.github.com
wrote:

**Comment by wejendorp** [comment]
Merge it! I have it under wraps ^^

**Pull request merged**
