### PR TITLE
Template fixes & improvements

### PR DESCRIPTION
**Pull request by jensraaby**
I was getting annoyed with all the "- PerSeq" titles so I've added a few to the existing templates.
Also adding commits with other HTML changes to this branch

### CODE REVIEW

**Comment by jensraaby** [comment]
I just added a change to the disease table view

TODO: add javascript table sorter

**Comment by paddie** [comment]
could you put in the disease field again?

**Comment by jensraaby** [comment]
Done...
I'm a bit time constrained at the moment so going to focus on the report for the time being...
Feel free to merge this in and I'll start a new PR when we have sorted out the next sprint plan

**Comment by paddie** [comment]
its still mixing together the snp and disease... let's hold of on this so we can decide which are the best ones. snpview is done btw.

**Pull request merged**
